spring:
    datasource:
        password: admin
        url: jdbc:postgresql://localhost:5432/db
        username: postgres
    jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect