spring:
    datasource:
        password: admin
        url: jdbc:postgresql://localhost:5432/db
        username: postgres
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        queue:
          name: demoqueue
        exchange:
          name: demoexchange
        routing:
          key: demokey
